name: result_type
version: 0.0.1
description: Result Type represents either a success or a failure, including an associated value in each case.
repository: https://github.com/epam-cross-platform-lab/dart_result_type

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  meta: ^1.2.4

dev_dependencies:
  http: ^0.12.2
  test: ^1.15.7