name: Dart

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
      - uses: actions/checkout@v2

      - name: Print Dart SDK version
        run: dart --version

      - name: Install dependencies
        run: dart pub get
        
      - name: Format
        run: dart format --set-exit-if-changed lib test example

      - name: Analyze project source
        run: dart analyze

#       - name: Run tests
#         run: dart test
